web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 -w 2 -k gevent --access-logfile - app:app
    ports:
        - "5000:5000"
    volumes:
        - .:/app
    links:
        - db
db:
    image: mongo:latest
